List sale = [
  {
    'Image':'asset/img/sale image/img12.png',
    'name' : 'Air Jordan XXXVII Low Guo PF 37 ',
    'prize': 140.00,
    'rating': 3.5,
    'public':2543,
    'qty':1,
  },
  {
    'Image':'asset/img/sale image/img2.png',
    'name' : 'Apple Smartwatch Series 7',
    'prize': 100.00,
    'rating': 4.5,
    'public':2372,
    'qty':1,
  },
  {
    'Image':'asset/img/sale image/img3.png',
    'name' : 'Sony WF-1000XM4 True Wireless',
    'prize':420.00,
    'rating': 4.2,
    'public':2480,
    'qty':1,
  },
  {
    'Image':'asset/img/sale image/img4.png',
    'name' : 'Sony WH-CH720N Noise Canceling',
    'prize':300.00,
    'rating': 4.0,
    'public':3200,
    'qty':1,
  },
  {
    'Image':'asset/img/sale image/img5.png',
    'name' : 'Ray-Ban Sunglasses Men',
    'prize':70.00,
    'rating': 3.8,
    'public':2952,
    'qty':1,
  },
];